- name: "Create app database"
  postgresql_db:
    state:                      present
    name:                       "{{ db_name }}"
  become:                       true
  become_user:                  postgres

- name: "Create db user"
  postgresql_user:
    state:                      present
    name:                       "{{ username }}"
    password:                   "{{ password }}"
    role_attr_flags:            "SUPERUSER" 
  become_user:                  postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type:                       database
    database:                   "{{ db_name }}"
    roles:                      "{{ username }}"
    grant_option:               no
    privs:                      all
  become_user:                  postgres

- name: "Allow md5 connection for the db user"
  template:
    src:                        "pg_hba.conf.j2"
    dest:                       "{{ postgresql_config_path }}/pg_hba.conf"
  notify:                       restart postgresql
  when:                         postgresql_hba_entries | length > 0