- name: "Make sure work directory is exists"
  file:                             
    path:                     /{{ data_path }}/
    state:                    directory 
    owner:                    root 
    group:                    root 
    mode:                     0777 
  when:                             data_path is defined

- name: make sure that work direcory exists
  file:                     
    path: /{{ data_path }}/redis 
    state:                    directory 
    group:                    redis 
    owner:                    redis 
    mode:                     0777 
  when:                             data_path is defined

- name: Ensure Redis Configuration
  template:                 
    src:                      redis.conf.j2 
    dest:                     /etc/redis/redis.conf 
    owner:                    root 
    group:                    root 
    mode:                     0777

- name: configure redis service
  template:                 
    src:                      redis-server.service.j2
    dest:                     /usr/lib/systemd/system/redis-server.service
    owner:                    root 
    group:                    root 
    mode:                     0777

- name: reload deamon after config
  shell:                      "systemctl daemon-reload"

- name: redis service is restarted
  service:                    
    name:                     redis 
    state:                    restarted