---
app_name:                 "bash_chrome"
db_name:                  "test"
username:                 "user"
password:                 "14092004"
postgresql_version:       "16"
postgresql_config_path:   "/etc/postgresql/16/main"
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: local, database: all, user: all, auth_method: md5 }
  - { type: local, database: all, user: user, auth_method: md5 }