---
- name: restart ssh
  service:
     name:                                 ssh
     state:                                restarted

- name: add port to inventory file
  delegate_to:                            localhost
  lineinfile:
    path:                                 "/{{ path_to_inventory }}/inventory/hosts.yml" 
    regexp:                               '^(\s*)ansible_ssh_port:\s*\d+'
    line:                                 '\1ansible_ssh_port: {{ ssh_port }}'
    backrefs:                             yes
    state:                                present